// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FBA2.Models
{
    [Table("appointments")]
    public partial class Appointments
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("title", TypeName = "text")]
        public string Title { get; set; }
        [Column("description", TypeName = "text")]
        public string Description { get; set; }
        [Column("apptDate", TypeName = "text")]
        public string ApptDate { get; set; }
        [Column("apptTime", TypeName = "text")]
        public string ApptTime { get; set; }
    }
}