// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FBA2.Models
{
    [Table("contacts")]
    public partial class Contacts
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("name", TypeName = "text")]
        public string Name { get; set; }
        [Column("email", TypeName = "text")]
        public string Email { get; set; }
        [Column("phone", TypeName = "text")]
        public string Phone { get; set; }
        [Column("birthday", TypeName = "text")]
        public string Birthday { get; set; }
    }
}