// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FBA2.Models
{
    [Table("notes")]
    public partial class Notes
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("title", TypeName = "text")]
        public string Title { get; set; }
        [Column("content", TypeName = "text")]
        public string Content { get; set; }
        [Column("color", TypeName = "text")]
        public string Color { get; set; }
    }
}