// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FBA2.Models
{
    [Table("tasks")]
    public partial class Tasks
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("description", TypeName = "text")]
        public string Description { get; set; }
        [Column("dueDate", TypeName = "text")]
        public string DueDate { get; set; }
        [Column("completed", TypeName = "text")]
        public string Completed { get; set; }
    }
}